//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Attendance.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnualLeave> AnnualLeaves { get; set; }
        public virtual DbSet<AttendanceData> AttendanceDatas { get; set; }
        public virtual DbSet<AttendanceTotal> AttendanceTotals { get; set; }
        public virtual DbSet<BranchDefaultWorkTime> BranchDefaultWorkTimes { get; set; }
        public virtual DbSet<BranchOperationPoint> BranchOperationPoints { get; set; }
        public virtual DbSet<ExchangeWorkData> ExchangeWorkDatas { get; set; }
        public virtual DbSet<LeaveRelation> LeaveRelations { get; set; }
        public virtual DbSet<OperationLog> OperationLogs { get; set; }
        public virtual DbSet<OutWorkPower> OutWorkPowers { get; set; }
        public virtual DbSet<OutWorkRecord> OutWorkRecords { get; set; }
        public virtual DbSet<OverTimeData> OverTimeDatas { get; set; }
        public virtual DbSet<OverWorkApply> OverWorkApplies { get; set; }
        public virtual DbSet<OverWorkDetail> OverWorkDetails { get; set; }
        public virtual DbSet<RestOverTime> RestOverTimes { get; set; }
        public virtual DbSet<SettingWorkDay> SettingWorkDays { get; set; }
        public virtual DbSet<WorkFlow> WorkFlows { get; set; }
        public virtual DbSet<WorkFlowDetail> WorkFlowDetails { get; set; }
        public virtual DbSet<WorkTime> WorkTimes { get; set; }
    }
}
