//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRS.Attendance.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutWorkRecord
    {
        public System.Guid ID { get; set; }
        public System.Guid PersonnelID { get; set; }
        public string OutReason { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public byte AuditState { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<System.Guid> AuditorID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public byte OutType { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUserID { get; set; }
        public string IPAddress { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<short> ApproverIndex { get; set; }
    }
}
